# Generated by Django 6.0.1 on 2026-01-19 22:07

import datetime
import diario.fields
import diario.models.movimiento
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import vvmodel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('sk', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('_plural', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', diario.fields.CaseInsensitiveCharField(max_length=100, unique=True)),
                ('sk', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z_\\-]*$', 'Solamente caracteres alfanuméricos y guiones')])),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('activa', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.moneda')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_dia', vvmodel.fields.PositionField(campo_colector='dia', colector_ordenado=True)),
                ('concepto', models.CharField(max_length=120)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('_importe', models.FloatField()),
                ('_cotizacion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sk', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('id_contramov', models.IntegerField(blank=True, null=True)),
                ('convierte_cuenta', models.CharField(blank=True, max_length=11, null=True, validators=[diario.models.movimiento.es_campo_cuenta_o_none])),
                ('es_automatico', models.BooleanField(default=False)),
                ('cta_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='diario.cuenta')),
                ('cta_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='diario.cuenta')),
                ('dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_set', to='diario.dia')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='diario.moneda')),
            ],
            options={
                'ordering': ('dia', 'orden_dia'),
            },
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('deudores', models.ManyToManyField(related_name='acreedores', to='diario.titular')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaAcumulativa',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diario.cuenta')),
                ('fecha_conversion', models.DateField()),
                ('titular_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_cuentas', to='diario.titular')),
            ],
            options={
                'abstract': False,
            },
            bases=('diario.cuenta',),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cta_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='diario.cuentaacumulativa'),
        ),
        migrations.CreateModel(
            name='CuentaInteractiva',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diario.cuenta')),
                ('_contracuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_cuentacontra', to='diario.cuentainteractiva')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='diario.titular')),
            ],
            options={
                'abstract': False,
            },
            bases=('diario.cuenta',),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_compra', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_venta', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField()),
                ('sk', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='diario.moneda')),
            ],
            options={
                'ordering': ('fecha',),
                'unique_together': {('fecha', 'moneda')},
            },
        ),
        migrations.CreateModel(
            name='SaldoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_importe', models.FloatField()),
                ('sk', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.cuenta')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.dia')),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('cuenta', 'dia')},
            },
        ),
    ]
