# Generated by Django 4.2.1 on 2023-10-15 00:52

import datetime
import diario.models.movimiento
import diario.models.titular
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ordered_field.ordered_collection_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z_\\-]*$', 'Solamente caracteres alfanuméricos y guiones')])),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', diario.models.movimiento.MiDateField(default=datetime.date.today)),
                ('orden_dia', django_ordered_field.ordered_collection_field.OrderedCollectionField(collection=('fecha',), default=-1, extra_field_updates={}, self_updates_on_collection_change={}, update_auto_now=True)),
                ('concepto', models.CharField(max_length=120)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('_importe', models.FloatField()),
                ('id_contramov', models.IntegerField(blank=True, null=True)),
                ('convierte_cuenta', models.CharField(blank=True, max_length=11, null=True, validators=[diario.models.movimiento.es_campo_cuenta_o_none])),
                ('es_automatico', models.BooleanField(default=False)),
                ('cta_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='diario.cuenta')),
                ('cta_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='diario.cuenta')),
            ],
            options={
                'ordering': ('fecha', 'orden_dia'),
            },
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titname', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('deudores', models.ManyToManyField(related_name='acreedores', to='diario.titular')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_importe', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.cuenta')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.movimiento')),
            ],
            options={
                'ordering': ['movimiento'],
                'unique_together': {('cuenta', 'movimiento')},
            },
        ),
        migrations.CreateModel(
            name='CuentaInteractiva',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diario.cuenta')),
                ('_contracuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_cuentacontra', to='diario.cuentainteractiva')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='diario.titular')),
            ],
            options={
                'abstract': False,
            },
            bases=('diario.cuenta',),
        ),
        migrations.CreateModel(
            name='CuentaAcumulativa',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diario.cuenta')),
                ('fecha_conversion', models.DateField()),
                ('titular_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_cuentas', to='diario.titular')),
            ],
            options={
                'abstract': False,
            },
            bases=('diario.cuenta',),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cta_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='diario.cuentaacumulativa'),
        ),
    ]
