# Generated by Django 3.2 on 2021-05-19 13:54
from datetime import date

import diario.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z]*$', 'Solamente caracteres alfanuméricos')])),
                ('saldo', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', diario.models.MiDateField(default=date.today)),
                ('concepto', models.CharField(max_length=80)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('importe', models.FloatField()),
                ('cta_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='diario.cuenta')),
                ('cta_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='diario.cuenta')),
            ],
            options={
                'ordering': ('fecha', 'concepto'),
            },
        ),
    ]
