# Generated by Django 4.2.1 on 2023-11-03 23:00

import diario.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=diario.fields.CaseInsensitiveCharField(max_length=100, unique=True),
        ),
    ]
