# Generated by Django 3.0.7 on 2020-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='detalle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
