# Generated by Django 4.2.1 on 2024-07-07 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='cotizacion',
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField()),
                ('fecha', models.DateField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='diario.moneda')),
            ],
            options={
                'ordering': ('fecha',),
                'unique_together': {('fecha', 'moneda')},
            },
        ),
    ]
