# Generated by Django 3.2 on 2021-05-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='opciones',
            field=models.CharField(default='i', max_length=8),
        ),
    ]
