# Generated by Django 3.2 on 2021-04-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
