# Generated by Django 3.2 on 2021-04-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=80)),
                ('detalle', models.TextField()),
                ('importe', models.FloatField()),
                ('cta_entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='diario.cuenta')),
                ('cta_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='diario.cuenta')),
            ],
        ),
    ]
