# Generated by Django 4.2.1 on 2024-01-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_movimiento_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.moneda'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='diario.moneda'),
        ),
    ]
