# Generated by Django 3.0.7 on 2020-08-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_auto_20200623_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='salida',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cta_entrada',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cta_salida',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
