# Generated by Django 3.2 on 2021-05-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_cuenta_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cta_madre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.cuenta'),
        ),
    ]
