# Generated by Django 3.2 on 2021-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_auto_20210419_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
