# Generated by Django 4.2.1 on 2023-11-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_cuenta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monname', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('cotizacion', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
