# Generated by Django 3.2 on 2021-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_cuenta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
    ]
