# Generated by Django 3.2 on 2021-05-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_cuenta_cta_madre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='saldo',
            new_name='_saldo',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cta_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='diario.cuenta'),
        ),
    ]
