# Generated by Django 3.2 on 2021-04-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_alter_cuenta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cta_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='diario.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cta_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='diario.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='detalle',
            field=models.TextField(blank=True),
        ),
    ]
