# Generated by Django 4.2.1 on 2025-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_movimiento__cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='importe',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='importe_compra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='importe_venta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
