# Generated by Django 4.2.1 on 2025-04-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_remove_cotizacion_importe_cotizacion_importe_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_set', to='diario.dia'),
        ),
    ]
