# Generated by Django 3.2 on 2021-04-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_alter_movimiento_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
