# Generated by Django 4.2.1 on 2023-11-16 01:18

import diario.utils.utils_moneda
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_alter_moneda_monname_alter_moneda_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='moneda',
            field=models.ForeignKey(default=diario.utils.utils_moneda.id_moneda_base, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='diario.moneda'),
        ),
    ]
