# Generated by Django 4.2.1 on 2025-04-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_alter_movimiento_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titular',
            old_name='sk',
            new_name='sk',
        ),
    ]
