# Generated by Django 3.2 on 2021-07-03 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diario', '0005_auto_20210701_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
