# Generated by Django 4.2.1 on 2023-11-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_movimiento_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='_plural',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
