# Generated by Django 4.2.1 on 2025-04-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_rename_titname_titular_sk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneda',
            old_name='sk',
            new_name='sk',
        ),
    ]
