# Generated by Django 3.2 on 2021-07-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_cuenta_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cta_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='diario.cuentaacumulativa'),
        ),
    ]
