# Generated by Django 3.2 on 2021-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_alter_cuenta_cta_madre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaacumulativa',
            name='fecha_conversion',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
