# Generated by Django 4.2.1 on 2025-04-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_rename_monname_moneda_sk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='slug',
            new_name='sk',
        ),
    ]
