# Generated by Django 4.2.1 on 2023-12-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_moneda__plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
