# Generated by Django 4.2.1 on 2025-04-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_rename_slug_cuenta_sk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titular',
            old_name='sk',
            new_name='_sk',
        ),
    ]
