# Generated by Django 4.2.1 on 2024-01-03 00:16

import diario.models.dia
from django.db import migrations, models
import django.db.models.deletion
import django_ordered_field.ordered_collection_field


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ('dia', 'orden_dia')},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='dia',
            field=models.ForeignKey(default=diario.models.dia.Dia.hoy, on_delete=django.db.models.deletion.CASCADE, to='diario.dia'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='orden_dia',
            field=django_ordered_field.ordered_collection_field.OrderedCollectionField(collection=('dia',), default=-1, extra_field_updates={}, self_updates_on_collection_change={}, update_auto_now=True),
        ),
    ]
