# Generated by Django 3.2 on 2021-08-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_cuentaacumulativa_fecha_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='opciones',
        ),
    ]
