# Generated by Django 3.2 on 2021-10-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_remove_cuenta_opciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titname', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
