# Generated by Django 4.2.1 on 2025-04-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_rename_sk_titular__sk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneda',
            old_name='sk',
            new_name='_sk',
        ),
    ]
