# Generated by Django 3.2 on 2021-10-09 12:15

import diario.models.titular
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentainteractiva',
            name='titular',
            field=models.ForeignKey(blank=True, default=diario.models.titular.Titular.por_defecto, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='diario.titular'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
