# Generated by Django 3.2 on 2021-10-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_auto_20211014_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(max_length=120),
        ),
    ]
