# Generated by Django 4.2.1 on 2025-04-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_rename_sk_cuenta__sk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='_sk',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='titular',
            name='_sk',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
