# Generated by Django 3.2 on 2021-10-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_alter_movimiento_concepto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='importe',
            new_name='_importe',
        ),
    ]
