# Generated by Django 3.2 on 2021-11-17 11:21

import diario.models.titular
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_rename_importe_movimiento__importe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentainteractiva',
            name='titular',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='titular',
            field=models.ForeignKey(blank=True, default=diario.models.titular.Titular.por_defecto, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='diario.titular'),
        ),
    ]
