# Generated by Django 4.2.1 on 2025-05-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_alter_moneda__sk_alter_titular__sk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_importe', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.cuenta')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.dia')),
            ],
            options={
                'unique_together': {('cuenta', 'dia')},
            },
        ),
    ]
