# Generated by Django 3.2 on 2021-12-01 00:15

import diario.models.titular
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0013_auto_20211117_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='titular',
            field=models.ForeignKey(blank=True, default=diario.models.titular.Titular.por_defecto, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='diario.titular'),
        ),
    ]
