# Generated by Django 4.2.1 on 2025-06-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0013_saldodiario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldodiario',
            options={'ordering': ['dia']},
        ),
    ]
