# Generated by Django 3.2 on 2021-12-01 01:42

from django.db import migrations
import django_ordered_field.ordered_collection_field


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0014_alter_cuenta_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='orden_dia',
            field=django_ordered_field.ordered_collection_field.OrderedCollectionField(collection=('fecha',), default=-1, extra_field_updates={}, self_updates_on_collection_change={}, update_auto_now=True),
        ),
    ]
