# Generated by Django 4.2.1 on 2025-06-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0014_alter_saldodiario_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
