# Generated by Django 4.2.1 on 2025-09-30 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0015_delete_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titular',
            old_name='_sk',
            new_name='sk',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='importe_compra',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='importe_venta',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='_cotizacion',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
