# Generated by Django 3.2 on 2021-12-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0015_movimiento_orden_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ('fecha', 'orden_dia')},
        ),
    ]
