# Generated by Django 3.2 on 2021-12-19 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0016_alter_movimiento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='slug',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z]*$', 'Solamente caracteres alfanuméricos')]),
        ),
    ]
