# Generated by Django 4.2.1 on 2025-09-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0016_rename__sk_titular_sk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneda',
            old_name='_sk',
            new_name='sk',
        ),
    ]
