# Generated by Django 4.2.1 on 2025-10-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0017_rename__sk_moneda_sk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='_sk',
            new_name='sk',
        ),
    ]
