# Generated by Django 3.2 on 2021-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0017_alter_cuenta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='id_contramov',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
