# Generated by Django 3.2 on 2021-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0018_movimiento_id_contramov'),
    ]

    operations = [
        migrations.AddField(
            model_name='titular',
            name='deudores',
            field=models.ManyToManyField(related_name='acreedores', to='diario.Titular'),
        ),
    ]
