# Generated by Django 4.2.1 on 2025-10-02 12:15

from django.db import migrations, models

def populate_sk_from_fecha(apps, schema_editor):
    Dia = apps.get_model('diario', 'Dia')
    for dia in Dia.objects.all():
        if dia.sk is None:
            dia.sk = dia.fecha.strftime("%Y%m%d")
            dia.full_clean()
            dia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0018_rename__sk_cuenta_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='sk',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.RunPython(
            populate_sk_from_fecha,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
