# Generated by Django 4.2.1 on 2025-10-02 20:36

from django.db import migrations, models


def populate_sk_from_fecha_and_moneda(apps, schema_editor):
    Cotizacion = apps.get_model('diario', 'Cotizacion')
    for cot in Cotizacion.objects.all():
        if cot.sk is None:
            Cotizacion.objects.filter(pk=cot.pk).update(sk=f"{cot.fecha.strftime('%Y%m%d')}{cot.moneda.sk}")


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0019_dia_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sk',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(
            populate_sk_from_fecha_and_moneda,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
