# Generated by Django 4.2.1 on 2025-10-02 23:34

from django.db import migrations, models


def populate_sk_from_fecha_and_cuenta(apps, schema_editor):
    SaldoDiario = apps.get_model('diario', 'saldodiario')
    for sd in SaldoDiario.objects.all():
        if sd.sk is None:
            sd.sk = f"{sd.dia.fecha.strftime('%Y%m%d')}{sd.cuenta.sk}"
            sd.full_clean()
            sd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0020_cotizacion_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldodiario',
            name='sk',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.RunPython(
            populate_sk_from_fecha_and_cuenta,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
