# Generated by Django 4.2.1 on 2025-10-06 21:23

from django.db import migrations, models


def populate_sk_from_dia_and_orden_dia(apps, schema_editor):
    Movimiento = apps.get_model('diario', 'movimiento')
    for mov in Movimiento.objects.all():
        if mov.sk is None:
            mov.sk = f"{mov.dia.sk}{mov.orden_dia:02d}"
            while Movimiento.objects.filter(sk=mov.sk).exists():
                mov.sk = str(int(mov.sk) + 1)
            mov.full_clean()
            mov.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0021_saldodiario_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='sk',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.RunPython(
            populate_sk_from_dia_and_orden_dia,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
