# Generated by Django 3.2 on 2022-01-08 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0021_alter_cuenta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentainteractiva',
            name='_contracuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_cuentacontra', to='diario.cuentainteractiva'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='slug',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z_\\-]*$', 'Solamente caracteres alfanuméricos y guiones')]),
        ),
    ]
