# Generated by Django 4.2.1 on 2025-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0022_movimiento_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
