# Generated by Django 3.2 on 2022-04-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0024_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldo',
            options={'ordering': ['fecha', 'cuenta']},
        ),
        migrations.AlterUniqueTogether(
            name='saldo',
            unique_together={('cuenta', 'fecha')},
        ),
    ]
