# Generated by Django 3.2 on 2022-04-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0026_cuenta_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldo',
            options={},
        ),
        migrations.AddField(
            model_name='saldo',
            name='movimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diario.movimiento'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='saldo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='fecha',
        ),
    ]
