# Generated by Django 3.2 on 2022-05-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0027_auto_20220426_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldo',
            options={'ordering': ['movimiento']},
        ),
        migrations.AlterUniqueTogether(
            name='saldo',
            unique_together={('cuenta', 'movimiento')},
        ),
    ]
