# Generated by Django 3.2 on 2022-05-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0028_auto_20220506_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldo',
            old_name='importe',
            new_name='_importe',
        ),
    ]
