# Generated by Django 3.2 on 2022-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0030_remove_cuenta__saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='convierte_cuenta',
            field=models.BooleanField(default=False),
        ),
    ]
