# Generated by Django 3.2 on 2022-07-09 13:23

import diario.models.movimiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0031_movimiento_convierte_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='convierte_cuenta',
            field=models.TextField(blank=True, null=True, validators=[diario.models.movimiento.es_campo_cuenta_o_none]),
        ),
    ]
