# Generated by Django 4.2.1 on 2023-06-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0033_remove_cuenta_titular_cuentainteractiva_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaacumulativa',
            name='titular_original',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_acum', to='diario.titular'),
            preserve_default=False,
        ),
    ]
