# Generated by Django 4.2.1 on 2023-06-25 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0034_cuentaacumulativa_titular_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaacumulativa',
            name='titular_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_cuentas', to='diario.titular'),
        ),
    ]
